generator:
  class: sfDoctrineGenerator
  param:
    model_class:           BetyoloBet
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          betyolo_bet
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        id: { label: "id" }
        description: { label: "mo ta" }
        category_id: { label: "Category" }
        status: { label: "status" }
      list:
        title: Bet Manager
        display:
          - id
          - description
          - category_id
          - status
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
