<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/12/22 14:42:03

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=betyolo',
  'username' => 'root',
  'password' => 'root',
  'attributes' => 
  array (
    'default_table_charset' => 'utf8',
    'default_table_collate' => 'utf8_general_ci',
  ),
  'name' => 'doctrine',
)),);
